on:
  push:
     branches:
       - main

name: deploy_book

jobs:
  blogdown:
    name: Render and deploy blogdown
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install r packages for blogdown
        run: |
          Rscript -e 'install.packages(c("bookdown", "rmarkdown"))'
  
      # - name: Install system dependencies
      #   if: runner.os == 'Linux'
      #   run: |
      #     # install spatial dependencies
      #     # sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
      #     sudo apt update
      #     sudo apt install \
      #       libudunits2-dev \
      #       libgdal-dev \
      #       libgeos-dev \
      #       libproj-dev \
      #       libmagick++-dev \
      #       imagemagick \
      #       ffmpeg \
      #       libpoppler-cpp-dev
                      
      # - name: Install r packages for posts
      #   run: |
      #     Rscript -e 'install.packages("pdftools")' \
      #             -e 'install.packages("tinytex")' \
      #             -e 'tinytex::install_tinytex()' \
      #             -e 'source("pkgs.R")'
                  
      # - name: install hugo
      #   run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.78.2")'
      - name: Render book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

      - name: Look at files
        run: ls ./_book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_book

